### ISSUE TITLE
Задание

### ISSUE THREAD

**Issue by igorevna-e04** [igorevna-e04/nkvt-zadanie#1]
Создать структуру папок в ветке acadmic:
- student
  - (имя 1 студента)
    - Создать About1.txt и написать в нем ФИО и номер группы
  - (имя 2 студента)
    - Создать About2.txt и написать в нем ФИО и номер группы

**Comment by EgorTomilov** [comment]
mkdir student 
cd student 
touch About1.txt
nano About1.txt
 FIO 273
touch About2.txt
 nano About2.txt
FIO1 273
